### ISSUE TITLE
o-pack spacing mixing is not applicable via @mixin

### ISSUE THREAD

**Issue by d-asensio** [haiticss/haiticss#83]
Could be great to modify the mixing o-pack--space to not to generate the css output of the selector but the border-spacing property, that way the user will be able to apply that spacing to its components via SCSS instead of classes in the markup.

Here you can see what I mean:

``` scss
@mixin o-pack--space($_space-name: "none", $_space-value: 0) {
  .o-pack--space-#{$_space-name} {
    border-spacing: s-core-px-to-rem($_space-value);
  }
}

// That's not doable.
.c-custom-component {
  @include o-pack();
  @include o-pack--space("none", 0);
  &__nested {
    @include o-pack__item();
  }
}
```

Also could be great to think in a way of using the spacing abstraction layer with this object too (see #64), now it's not possible because o-pack uses the `border-spacing` property instead of the `margin` property.

@danifornells @arnau-pujol @judabelli what do you think about?
